/* auto-generated by NAPI-RS-OHOS */
/* eslint-disable */
export interface Input {
  left: number
  right: number
}

export interface Output {
  result: number
}

export interface VersionInfoRequestModel {
  strParam: string
  intParam: number
}

export interface VersionInfoResponseModel {
  versionName: string
  versionCode: number
}

export declare function add(left: number, right: number): number

export declare function addInput(input: Input): Output

export declare function asyncAdd(left: number, right: number): Promise<number>

export declare function asyncMinus(left: number, right: number): Promise<number>

/** 同步回调，即rust调用js/ts/arkts的同步函数，带复杂入参 */
export declare function getVersionInfo(jsFunction: (arg: VersionInfoRequestModel) => VersionInfoResponseModel): VersionInfoResponseModel

/** 异步回调，即rust调用js/ts/arkts的异步函数，带复杂出参 */
export declare function getVersionInfoAsync(jsPromise: Promise<VersionInfoResponseModel>): Promise<VersionInfoResponseModel>

/** 异步回调，即rust调用js/ts/arkts的异步函数，带复杂入参和出参 */
export declare function getVersionInfoAsyncWithInput(tsfn: (err: Error | null, arg: VersionInfoRequestModel) => Promise<VersionInfoResponseModel>): Promise<VersionInfoResponseModel>

/** 同步回调，即rust调用js/ts/arkts的同步函数，带String入参 */
export declare function getVersionName(jsFunction: (arg: string) => string): string

/** 异步回调，即rust调用js/ts/arkts的异步函数，无入参 */
export declare function getVersionNameAsync(jsPromise: Promise<string>): Promise<string>

