// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD0
typedef void (*UniffiCallbackInterfaceAndroidDelegateMethod0)(uint64_t, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD1
typedef void (*UniffiCallbackInterfaceAndroidDelegateMethod1)(uint64_t, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD2
typedef void (*UniffiCallbackInterfaceAndroidDelegateMethod2)(uint64_t, RustBuffer, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_ANDROID_DELEGATE_METHOD3
typedef void (*UniffiCallbackInterfaceAndroidDelegateMethod3)(uint64_t, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CALLBACK_TRAIT_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CALLBACK_TRAIT_METHOD0
typedef void (*UniffiCallbackInterfaceCallbackTraitMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ANDROID_DELEGATE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_ANDROID_DELEGATE
typedef struct UniffiVTableCallbackInterfaceAndroidDelegate {
    UniffiCallbackInterfaceAndroidDelegateMethod0 _Nonnull getAndroidConfig;
    UniffiCallbackInterfaceAndroidDelegateMethod1 _Nonnull getCurrentActivity;
    UniffiCallbackInterfaceAndroidDelegateMethod2 _Nonnull logD;
    UniffiCallbackInterfaceAndroidDelegateMethod3 _Nonnull getSystemTime;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceAndroidDelegate;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CALLBACK_TRAIT
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CALLBACK_TRAIT
typedef struct UniffiVTableCallbackInterfaceCallbackTrait {
    UniffiCallbackInterfaceCallbackTraitMethod0 _Nonnull call;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceCallbackTrait;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_CLONE_MATHMANAGER
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_CLONE_MATHMANAGER
void*_Nonnull uniffi_rust_lib_fn_clone_mathmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FREE_MATHMANAGER
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FREE_MATHMANAGER
void uniffi_rust_lib_fn_free_mathmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_CONSTRUCTOR_MATHMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_CONSTRUCTOR_MATHMANAGER_NEW
void*_Nonnull uniffi_rust_lib_fn_constructor_mathmanager_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_METHOD_MATHMANAGER_MULTIPLY
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_METHOD_MATHMANAGER_MULTIPLY
int32_t uniffi_rust_lib_fn_method_mathmanager_multiply(void*_Nonnull ptr, int32_t left, int32_t right, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_METHOD_MATHMANAGER_TEST_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_METHOD_MATHMANAGER_TEST_CALLBACK
void uniffi_rust_lib_fn_method_mathmanager_test_callback(void*_Nonnull ptr, uint64_t callback, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_INIT_CALLBACK_VTABLE_ANDROIDDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_INIT_CALLBACK_VTABLE_ANDROIDDELEGATE
void uniffi_rust_lib_fn_init_callback_vtable_androiddelegate(UniffiVTableCallbackInterfaceAndroidDelegate* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_INIT_CALLBACK_VTABLE_CALLBACKTRAIT
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_INIT_CALLBACK_VTABLE_CALLBACKTRAIT
void uniffi_rust_lib_fn_init_callback_vtable_callbacktrait(UniffiVTableCallbackInterfaceCallbackTrait* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ADD
int32_t uniffi_rust_lib_fn_func_add(int32_t left, int32_t right, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ADD_INPUT
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ADD_INPUT
RustBuffer uniffi_rust_lib_fn_func_add_input(RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ASYNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_ASYNC_ADD
uint64_t uniffi_rust_lib_fn_func_async_add(int32_t left, int32_t right
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_INIT
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_INIT
uint64_t uniffi_rust_lib_fn_func_init(uint64_t delegate
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_IS_ODD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_FN_FUNC_IS_ODD
uint64_t uniffi_rust_lib_fn_func_is_odd(int32_t num
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_ALLOC
RustBuffer ffi_rust_lib_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_rust_lib_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_FREE
void ffi_rust_lib_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUSTBUFFER_RESERVE
RustBuffer ffi_rust_lib_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U8
void ffi_rust_lib_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U8
void ffi_rust_lib_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U8
void ffi_rust_lib_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_rust_lib_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I8
void ffi_rust_lib_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I8
void ffi_rust_lib_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I8
void ffi_rust_lib_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I8
int8_t ffi_rust_lib_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U16
void ffi_rust_lib_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U16
void ffi_rust_lib_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U16
void ffi_rust_lib_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_rust_lib_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I16
void ffi_rust_lib_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I16
void ffi_rust_lib_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I16
void ffi_rust_lib_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I16
int16_t ffi_rust_lib_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U32
void ffi_rust_lib_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U32
void ffi_rust_lib_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U32
void ffi_rust_lib_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_rust_lib_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I32
void ffi_rust_lib_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I32
void ffi_rust_lib_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I32
void ffi_rust_lib_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I32
int32_t ffi_rust_lib_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_U64
void ffi_rust_lib_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_U64
void ffi_rust_lib_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_U64
void ffi_rust_lib_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_rust_lib_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_I64
void ffi_rust_lib_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_I64
void ffi_rust_lib_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_I64
void ffi_rust_lib_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_I64
int64_t ffi_rust_lib_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_F32
void ffi_rust_lib_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_F32
void ffi_rust_lib_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_F32
void ffi_rust_lib_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_F32
float ffi_rust_lib_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_F64
void ffi_rust_lib_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_F64
void ffi_rust_lib_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_F64
void ffi_rust_lib_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_F64
double ffi_rust_lib_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_POINTER
void ffi_rust_lib_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_POINTER
void ffi_rust_lib_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_POINTER
void ffi_rust_lib_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_rust_lib_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_rust_lib_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_rust_lib_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_rust_lib_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_rust_lib_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_POLL_VOID
void ffi_rust_lib_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_CANCEL_VOID
void ffi_rust_lib_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_FREE_VOID
void ffi_rust_lib_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_RUST_LIB_RUST_FUTURE_COMPLETE_VOID
void ffi_rust_lib_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ADD
uint16_t uniffi_rust_lib_checksum_func_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ADD_INPUT
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ADD_INPUT
uint16_t uniffi_rust_lib_checksum_func_add_input(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ASYNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_ASYNC_ADD
uint16_t uniffi_rust_lib_checksum_func_async_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_INIT
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_INIT
uint16_t uniffi_rust_lib_checksum_func_init(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_IS_ODD
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_FUNC_IS_ODD
uint16_t uniffi_rust_lib_checksum_func_is_odd(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_MATHMANAGER_MULTIPLY
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_MATHMANAGER_MULTIPLY
uint16_t uniffi_rust_lib_checksum_method_mathmanager_multiply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_MATHMANAGER_TEST_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_MATHMANAGER_TEST_CALLBACK
uint16_t uniffi_rust_lib_checksum_method_mathmanager_test_callback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_CONSTRUCTOR_MATHMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_CONSTRUCTOR_MATHMANAGER_NEW
uint16_t uniffi_rust_lib_checksum_constructor_mathmanager_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_ANDROID_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_ANDROID_CONFIG
uint16_t uniffi_rust_lib_checksum_method_androiddelegate_get_android_config(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_CURRENT_ACTIVITY
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_CURRENT_ACTIVITY
uint16_t uniffi_rust_lib_checksum_method_androiddelegate_get_current_activity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_LOG_D
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_LOG_D
uint16_t uniffi_rust_lib_checksum_method_androiddelegate_log_d(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_SYSTEM_TIME
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_ANDROIDDELEGATE_GET_SYSTEM_TIME
uint16_t uniffi_rust_lib_checksum_method_androiddelegate_get_system_time(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_CALLBACKTRAIT_CALL
#define UNIFFI_FFIDEF_UNIFFI_RUST_LIB_CHECKSUM_METHOD_CALLBACKTRAIT_CALL
uint16_t uniffi_rust_lib_checksum_method_callbacktrait_call(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_RUST_LIB_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_RUST_LIB_UNIFFI_CONTRACT_VERSION
uint32_t ffi_rust_lib_uniffi_contract_version(void
    
);
#endif

